[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.34.0", features = ["csv", "describe"] }
linfa = "0.7.0"
linfa-trees = "0.7.0"
ndarray = "0.15.3"
chrono = "0.4.41"
